version: 2

sources:
  - name: analytics_raw
    description: "Tables brutes chargées depuis Parquet (10 villes européennes)"
    schema: analytics
    
    tables:
      - name: cities_raw
        description: "Métadonnées géographiques des 10 villes"
        columns:
          - name: city
            description: "Nom de la ville"
            tests:
              - not_null
              - unique
          
          - name: country
            description: "Nom du pays (ex: France, Germany)"
          
          - name: country_code
            description: "Code ISO pays (FR, DE, ES...)"
            tests:
              - not_null
          
          - name: admin1
            description: "Région administrative"
          
          - name: timezone
            description: "Fuseau horaire IANA (Europe/Paris...)"
          
          - name: latitude
            description: "Latitude (degrés décimaux)"
          
          - name: longitude
            description: "Longitude (degrés décimaux)"
          
          - name: population
            description: "Population de la ville"
            tests:
              - not_null
      
      - name: weather_hourly_raw
        description: "Données météo horaires (7 jours × 10 villes)"
        columns:
          - name: city
            description: "Nom de la ville"
            tests:
              - not_null
          
          - name: country_code
            description: "Code ISO pays"
          
          - name: time_utc
            description: "Timestamp UTC"
            tests:
              - not_null
          
          - name: temperature_2m
            description: "Température °C"
          
          - name: humidity_2m
            description: "Humidité %"
          
          - name: precipitation
            description: "Précipitations mm"
          
          - name: wind_speed_10m
            description: "Vent km/h"