dbt_weather_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost  # ← Ou l'IP du conteneur
      user: postgres
      password: postgres
      port: 5432
      dbname: datalake
      schema: analytics
      threads: 4